Frontend/website/userProfile/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt
from .views import UserProfile, UserRecommendations, UserBooks, tbrBooks, rateBook
app_name = 'userProfile'
urlpatterns = [
    path('recommendations', views.UserRecommendations.as_view(), name='userrecommendations'),
    path('recommendationsPage', views.recommendationsPage.as_view(), name='userrecommendationspage'),
    path('userhome', views.UserProfile, name='userhome'),
    path('userbooks', views.UserBooks.as_view(), name='userbooks'),
    path('tbrbooks', views.tbrBooks.as_view(), name='tbrbooks'),
    #path('browsebooks',views.browseBooks.as_view(), name='browseBooks'),
    path('userbooks/ratebook', views.rateBook.as_view(), name='ratebook'),
    path('userbooks/reviewbook', views.reviewBook.as_view(), name='reviewbook'),
    path('userhome/to-read-next', views.setToReadNext.as_view(), name='to-read-next'),
    path('book/<str:book_id>', views.bookDetails, name='book-details'),
    path('browseBooks/genre/<str:genre>/<int:pageNumber>', views.getGenre, name='get-genre'),
    path('browseBooks/want-to-read-browse', views.wantToReadBrowse, name='want-to-read-browse'),
    path('book/want-to-read/<str:book_id>', views.wantToReadBookDetails, name='want-to-read-book-details'),
    path('search', views.searchBooks, name='search-books'),
    path('searchinread', views.searchInRead, name='search-in-read'),
    path('searchintbr', views.searchInTbr, name='search-in-tbr'),
    path('setreadinggoal', views.setReadingGoal, name='set-reading-goal'),
    path('deletetbr/<str:book_id>',views.deleteFromTbr, name='delete-tbr'),
    path('deleteread/<str:book_id>/<int:rating>',views.deleteFromRead, name='delete-read'),
    path('setcurrentbook/<str:book_id>',views.setCurrentBook, name='set-current-book'),

]

Frontend/website/website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('mainPage.urls')),
    path('authentication/', include('authentication.urls')),
    path("admin/", admin.site.urls),
    path('userProfile/', include('userProfile.urls')),

]

Frontend/website/templates/auth_base.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>auth</title>




    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="{% static 'css/authenstyle.css'%}" rel="stylesheet" >
    <link href="{% static 'css/bootstrap.css'%}" rel="stylesheet" >

    <link   rel="stylesheet" 
        href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" 
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" 
        crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" 
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" 
        crossorigin="anonymous">
    </script>
  </head>
  <header>
    <!--{% include 'partials/_navbar.html' %}-->
  </header>

<body class="text-center">

<main class="form-signin w-100 m-auto">
  
{% block content %}

{% endblock %}
</main>


    
</body>
</html>

Frontend/website/templates/base.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> NextReads {% block title %}
        {% endblock %}
    </title>

<link href="{% static 'css/bootstrap.css'%}" rel="stylesheet" >
<link href="{% static 'css/main.css'%}" rel="stylesheet" >


   
    <!-- Custom styles for this template -->
    <link href="{% static 'css/carousel.css'%}" rel="stylesheet">
  </head>
  <body>
    
  <header>
      {% include 'partials/_navbar.html' %}
  </header>

    <script src="{% static 'js/bootstrap.bundle.min.js'%}"></script>
<main>

  <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner"  >
      <div class="carousel-item active" >
        <img class="bd-placeholder-img" width="100%" height="100%" src="https://images.gr-assets.com/misc/1597342101-1597342101_goodreads_misc.gif">
        <div class="container">
          <div class="carousel-caption mark " >
            <div>
            <h1 >NextReads</h1>
            <p>Deciding what to read next?</p>
            <p><a class="btn btn-lg btn-primary" href='/authentication/signup'>Sign up today</a></p>
            </div>
            <div>
              Already a member?
              <a class="float-center" href="/authentication/login">sign in</a>
            </div>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <img class="bd-placeholder-img" width="100%" height="100%" src="https://orion-uploads.openroadmedia.com/lg_f7a2e2324ae5-download-(2).jpeg">
        <div class="container">
          <div class="carousel-caption mark">
            <h1>Another example headline.</h1>
            <p>Some representative placeholder content for the second slide of the carousel.</p>
            <p><a class="btn btn-lg btn-primary" href="#">Learn more</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <img class="bd-placeholder-img" width="100%" height="100%" src="https://media-cldnry.s-nbcnews.com/image/upload/newscms/2023_05/1962836/colleen-hoover-books-2x1-jp-230130.jpg">
        <div class="container">
          <div class="carousel-caption mark">
            <h1>One more for good measure.</h1>
            <p>Some representative placeholder content for the third slide of this carousel.</p>
            <p><a class="btn btn-lg btn-primary" href="#">Browse gallery</a></p>
          </div>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>


  <!-- Marketing messaging and featurettes
  ================================================== -->
  <!-- Wrap the rest of the page in another container to center all the content. -->

  <div class="container marketing">

    <!-- Three columns of text below the carousel -->
    <div class="row">
      <div class="col-lg-4">
        <img src = "{% static 'img/medal-svgrepo-com.svg'%}" width="140" height="140" alt="MySVG"/>
        <h2 class="fw-normal">Top rated this month</h2>
        <p>Some representative placeholder content for the three columns of text below the carousel. This is the first column.</p>
        <p><a class="btn btn-secondary" href="#">View details &raquo;</a></p>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">
        <!-- <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"/><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text></svg>-->
        <img src = "{% static 'img/best-practices-2-svgrepo-com.svg'%}" width="140" height="140" alt="MySVG"/>
        <h2 class="fw-normal">Top rated this week</h2>
        <p>Another exciting bit of representative placeholder content. This time, we've moved on to the second column.</p>
        <p><a class="btn btn-secondary" href="#">View details &raquo;</a></p>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">
        <img src = "{% static 'img/best-practices-svgrepo-com.svg'%}" width="140" height="140" alt="MySVG"/>
        <h2 class="fw-normal">Best books 2022</h2>
        <p>And lastly this, the third column of representative placeholder content.</p>
        <p><a class="btn btn-secondary" href="#">View details &raquo;</a></p>
      </div><!-- /.col-lg-4 -->
    </div><!-- /.row -->


    <!-- START THE FEATURETTES -->

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading fw-normal lh-1">Deciding what to read next? <span class="text-muted">It’ll blow your mind.</span></h2>
        <p class="lead">You’re in the right place. Tell us what titles or genres you’ve enjoyed in the past, and we’ll give you surprisingly insightful recommendations.</p>
      </div>
      <div class="col-md-5">
        <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" src="https://images.gr-assets.com/misc/1682027733-1682027733_goodreads_misc.png">
      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7 order-md-2">
        <h2 class="featurette-heading fw-normal lh-1">“A reader lives a thousand lives before he dies . . . The man who never reads lives only one.” </h2>
        <p class="lead">George R.R. Martin (American novelist and short-story writer, screenwriter, and television producer.)</p>
      </div>
      <div class="col-md-5 order-md-1">
        <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" src="https://cdn.britannica.com/05/223205-050-8931FF28/American-writer-George-RR-Martin-2011.jpg">
      </div>
    </div>

    <hr class="featurette-divider">

    <!-- /END THE FEATURETTES -->

  </div><!-- /.container -->


  <!-- FOOTER -->
  <footer class="container">
    <p class="float-end"><a href="#">Back to top</a></p>
    <p>&copy; 2017–2022 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
  </footer>
</main>


    <script src=" {% static 'js/main.js' %}" ></script>
  </body>
</html>

Frontend/website/templates/bookDetails.html
{% extends 'userprofile/userprofile_base.html' %} {% load static %} 
{% block content %}

<head>
    <title>Book Details Page</title>
    <style>
      /* Custom CSS */
      .book-image {
        max-width: 100%;
        height: auto;
      }
      .rating-stars {
        margin-top: 10px;
      }
      .similar-books {
        margin-top: 30px;
      }
      .carousel-control-prev-icon,
      .carousel-control-next-icon {
        filter: invert(100%); /* Invert the color to black */
    }
    .carousel-control-prev,
    .carousel-control-next {
        width: 5%;
    }
    .carousel-item img {
        width: 130px;
        height: auto;
        border-radius: 5px;
    }
    .responsive-img {
        display: block;
        height: auto;
        width: 200px;
        border-radius: 5px;
    }
    
    .stars .fa-star {
  color: grey;
}
.rmv-btn {
  padding: 0;
  border: none;
  border-color: transparent !important;
  background: transparent !important;

}

/* prev siblings should be orange */
.stars:hover .fa-star{
  color: orange;
}

.stars .fa-star:hover ~ .fa-star {
  color: grey;
}

.star-rating {
  margin: 0px 0 0px;
  font-size: 0;
  white-space: nowrap;
  display: inline-block;
  width: 175px;
  height: 35px;
  overflow: hidden;
  position: relative;
  background: url('data:image/svg+xml;base64,PHN2ZyB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHg9IjBweCIgeT0iMHB4IiB3aWR0aD0iMjBweCIgaGVpZ2h0PSIyMHB4IiB2aWV3Qm94PSIwIDAgMjAgMjAiIGVuYWJsZS1iYWNrZ3JvdW5kPSJuZXcgMCAwIDIwIDIwIiB4bWw6c3BhY2U9InByZXNlcnZlIj48cG9seWdvbiBmaWxsPSIjREREREREIiBwb2ludHM9IjEwLDAgMTMuMDksNi41ODMgMjAsNy42MzkgMTUsMTIuNzY0IDE2LjE4LDIwIDEwLDE2LjU4MyAzLjgyLDIwIDUsMTIuNzY0IDAsNy42MzkgNi45MSw2LjU4MyAiLz48L3N2Zz4=');
  background-size: contain;
 }

.star-rating i {
  opacity: 0;
  position: absolute;
  left: 0;
  top: 0;
  height: 100%;
  width: 20%;
  z-index: 1;
  background: url('data:image/svg+xml;base64,PHN2ZyB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHg9IjBweCIgeT0iMHB4IiB3aWR0aD0iMjBweCIgaGVpZ2h0PSIyMHB4IiB2aWV3Qm94PSIwIDAgMjAgMjAiIGVuYWJsZS1iYWNrZ3JvdW5kPSJuZXcgMCAwIDIwIDIwIiB4bWw6c3BhY2U9InByZXNlcnZlIj48cG9seWdvbiBmaWxsPSIjRkZERjg4IiBwb2ludHM9IjEwLDAgMTMuMDksNi41ODMgMjAsNy42MzkgMTUsMTIuNzY0IDE2LjE4LDIwIDEwLDE2LjU4MyAzLjgyLDIwIDUsMTIuNzY0IDAsNy42MzkgNi45MSw2LjU4MyAiLz48L3N2Zz4=');
  background-size: contain;
}

.star-rating input {
  opacity: 0;
  display: inline-block;
  width: 20%;
  height: 100%;
  margin: 0;
  padding: 0;
  z-index: 2;
  position: relative;
}

.star-rating input:hover + i,
.star-rating input:checked + i {
  opacity: 1;
}
.star-rating i ~ i {
  width: 40%;
}
.star-rating i ~ i ~ i {
  width: 60%;
}
.star-rating i ~ i ~ i ~ i {
  width: 80%;
}
.star-rating i ~ i ~ i ~ i ~ i {
  width: 100%;
}




    </style>
  </head>
  <body>
    <div class="container">
      <div class="row">
        {% include 'partials/_messages.html' %}

        <!-- First Column -->
        <div class="col-md-4">
          <img   class="responsive-img" src="{{book.imageUrl}}" alt="Book Image" class="book-image">
          <div class="rating-stars">
            <form method="POST" action="{%  url 'userProfile:ratebook' %}">
                {% csrf_token %}

                <input type="hidden" name="fe_eh" value="{{ book.id }}" />
                <span class="star-rating">
                  <input  type="radio" name="rating" value="1"><i></i>
                  <input  type="radio" name="rating" value="2"><i></i>
                  <input  type="radio" name="rating" value="3"><i></i>
                  <input  type="radio" name="rating" value="4"><i></i>
                  <input  type="radio" name="rating" value="5"><i></i>
                </span><br>
                <button type="submit"  class="btn btn-sm btn-outline-secondary mt-2 ">Save rate</button>
            </form>
          </div>
          <div>
            <!-- Buttons -->
            <div class="dropdown">
                <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                  Want to read
                </a>
              
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                  <li><a class="dropdown-item" href="{% url 'userProfile:want-to-read-book-details' book_id=book.id %}">Want to read</a></li>
                  <li><a class="dropdown-item" href="{% url 'userProfile:set-current-book' book_id=book.id %}">Currently reading</a></li>
                </ul>
              </div>
            </div>
        </div>
        <!-- Second Column -->
        <div class="col-md-8">
          <h1>{{book.title}}</h1>
          <p>{{book.description1}}</p>
          <div class="collapse" id="collapseExample">
            {{book.description2}}
          </div>
          <div class="mb-3">
            <a class= "link" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
              continue reading
            </a>
          </div>
          <p><strong style="color:#2D9EDE">Authors: </strong>          
            {% for author in book.authors %}
            {{author.full_name}}, 
            {% endfor %}
          </p>
         
          <p><strong style="color:#2D9EDE">Genres: </strong> {{book.genres}}</p>


          <div class="similar-books my-5">
            <h3>Similar Books</h3>

            <!-- Sliding Section for Similar Books -->
            <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-controls">
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleSlidesOnly" data-bs-slide="prev">
                      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                      <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleSlidesOnly" data-bs-slide="next">
                      <span class="carousel-control-next-icon" aria-hidden="true"></span>
                      <span class="visually-hidden">Next</span>
                    </button>
                  </div> 

              <div class="carousel-inner px-5">
                
                {% for book in similarbooks %}
                {% if forloop.counter0|divisibleby:4 %}
                <div class="carousel-item {% if forloop.counter0 == 0 %} active {% endif %}">
                    <div class="row">
                        {% endif %}
                        <div class="col-lg-3 col-md-6 col-sm-6 my-2 h-100">
                          <a href="{% url 'userProfile:book-details' book_id=book.id %}">
                            <img src="{{book.imageUrl}}" class="d-block" alt="Book 1">
                          </a>
                          <p>{{book.title}}</p>
                        </div>
                        {% if forloop.counter|divisibleby:4 %}
                      </div>
                </div>
                {% endif %}
                {% endfor %}

<!--                 
                <div class="carousel-item active">
                    <div class="row">
                        <div class="col-lg-3 col-md-6 col-sm-6 my-2">
                          <img src="https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1524322945i/34499221.jpg" class="d-block" alt="Book 1">
                          <p>book title</p>
                        </div>
                        <div class="col-lg-3 col-md-6 col-sm-6 my-2">
                          <img  src="https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1524322945i/34499221.jpg" class="d-block" alt="Book 2">
                          <p>book title</p>
                        </div>
                        <div class="col-lg-3 col-md-6 col-sm-6 my-2">
                          <img src="https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1524322945i/34499221.jpg"  class="d-block" alt="Book 3">
                          <p>book title</p>
                        </div>
                        <div class="col-lg-3 col-md-6 col-sm-6 my-2">
                            <img src="https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1524322945i/34499221.jpg"  class="d-block" alt="Book 3">
                          <p>book title</p>
                          </div>
                      </div>
                </div>


                <div class="carousel-item">
                    <div class="row">
                        <div class="col-lg-3 col-md-6 col-sm-6 my-2">
                          <img src="https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1524322945i/34499221.jpg" class="d-block" alt="Book 1">
                          <p>book title</p>
                        </div>
                        <div class="col-lg-3 col-md-6 col-sm-6 my-2">
                          <img src="https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1524322945i/34499221.jpg" class="d-block" alt="Book 2">
                          <p>book title</p>
                        </div>
                        <div class="col-lg-3 col-md-6 col-sm-6 my-2">
                          <img src="https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1524322945i/34499221.jpg" class="d-block" alt="Book 3">
                          <p>book title</p>
                        </div>
                        <div class="col-lg-3 col-md-6 col-sm-6 my-2">
                            <img src="https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1524322945i/34499221.jpg"  class="d-block" alt="Book 3">
                            <p>book title</p>
                          </div>
                      </div>
                </div>


                <div class="carousel-item">
                    <div class="row">
                        <div class="col-lg-3 col-md-6 col-sm-6 my-2">
                          <img  src="https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1524322945i/34499221.jpg"  class="d-block" alt="Book 1">
                          <p>book title</p>
                        </div>
                        <div class="col-lg-3 col-md-6 col-sm-6 my-2">
                          <img src="https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1524322945i/34499221.jpg"  class="d-block" alt="Book 2">
                          <p>book title</p>
                        </div>
                        <div class="col-lg-3 col-md-6 col-sm-6 my-2">
                          <img src="https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1524322945i/34499221.jpg"  class="d-block" alt="Book 3">
                          <p>book title</p>
                        </div>
                        <div class="col-lg-3 col-md-6 col-sm-6 my-2">
                            <img src="https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1524322945i/34499221.jpg"  class="d-block" alt="Book 3">
                            <p>book title</p>
                          </div>
                      </div>
                </div> -->

              </div>
              
          
            </div> <!-- End of Sliding Section -->
            
          </div>
        </div>
        
      </div>
    </div>

  </body>
{% endblock %}
<!-- <link href="{% static 'css/bootstrap.css'%}" rel="stylesheet" /> -->

<!-- <script src="{% static 'js/bootstrap.bundle.min.js'%}"></script> -->

Frontend/website/templates/register_steps_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Register Steps</title>
    <link href="{% static 'css/registerr.css'%}" rel="stylesheet" />

    <link href="{% static 'css/bootstrap.css'%}" rel="stylesheet" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, 0.1);
        border: solid rgba(0, 0, 0, 0.15);
        border-width: 1px 0;
        box-shadow: inset 0 0.5em 1.5em rgba(0, 0, 0, 0.1),
          inset 0 0.125em 0.5em rgba(0, 0, 0, 0.15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -0.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>

    <!-- Custom styles for this template -->
  </head>
  <body>
    <header
      class="navbar navbar-nav navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow"
    >
    <div class="container-fluid">
      <div>
        <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6" href="/"
          >NextReads</a
        >
      </div>

      <div style ="display: flex; align-items: center; padding: 20px 110px 10px;">
        <button id="progress-prev" class="btn btn-secondary">Prev</button>
        <div id="progress">
          <div id="progress-bar"></div>
          <ul id="progress-num">
            <li class="step active">1</li>
            <li class="step">2</li>
            <li class="step">2</li>
          </ul>
        </div>
        <button id="progress-next" class="btn btn-secondary">Next</button>
      </div>
      <div >
        <button
          class="navbar-toggler position-absolute d-md-none collapsed"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#sidebarMenu"
          aria-controls="sidebarMenu"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
    </div>
    </header>
    <script  defer type="text/javascript" src="{% static 'js/progresssteps.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    {% block content %} {% endblock %}

   
  </body>
</html>