Frontend/website/userProfile/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt
from .views import UserProfile, UserRecommendations, UserBooks, tbrBooks, rateBook
app_name = 'userProfile'
urlpatterns = [
    path('recommendations', views.UserRecommendations.as_view(), name='userrecommendations'),
    path('recommendationsPage', views.recommendationsPage.as_view(), name='userrecommendationspage'),
    path('userhome', views.UserProfile, name='userhome'),
    path('userbooks', views.UserBooks.as_view(), name='userbooks'),
    path('tbrbooks', views.tbrBooks.as_view(), name='tbrbooks'),
    #path('browsebooks',views.browseBooks.as_view(), name='browseBooks'),
    path('userbooks/ratebook', views.rateBook.as_view(), name='ratebook'),
    path('userbooks/reviewbook', views.reviewBook.as_view(), name='reviewbook'),
    path('userhome/to-read-next', views.setToReadNext.as_view(), name='to-read-next'),
    path('book/<str:book_id>', views.bookDetails, name='book-details'),
    path('browseBooks/genre/<str:genre>/<int:pageNumber>', views.getGenre, name='get-genre'),
    path('browseBooks/want-to-read-browse', views.wantToReadBrowse, name='want-to-read-browse'),
    path('book/want-to-read/<str:book_id>', views.wantToReadBookDetails, name='want-to-read-book-details'),
    path('search', views.searchBooks, name='search-books'),
    path('searchinread', views.searchInRead, name='search-in-read'),
    path('searchintbr', views.searchInTbr, name='search-in-tbr'),
    path('setreadinggoal', views.setReadingGoal, name='set-reading-goal'),
    path('deletetbr/<str:book_id>',views.deleteFromTbr, name='delete-tbr'),
    path('deleteread/<str:book_id>/<int:rating>',views.deleteFromRead, name='delete-read'),
    path('setcurrentbook/<str:book_id>',views.setCurrentBook, name='set-current-book'),

]

Frontend/website/website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('mainPage.urls')),
    path('authentication/', include('authentication.urls')),
    path("admin/", admin.site.urls),
    path('userProfile/', include('userProfile.urls')),

]

Frontend/website/userProfile/models.py
from django.db import models

# Create your models here.

Frontend/website/userProfile/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.views import View
from django.contrib import messages
from django.http import JsonResponse

from config import domainName


import requests

# Create your views here.
def getToReadNext(request):
        try:
            userToken = request.session.get('token')
            headers = {'x-auth-token': userToken}
            toReadNextResponse = requests.get(f'{domainName}/api/users/toreadnext', headers=headers)
            if toReadNextResponse.status_code == 200:
                toReadNext = toReadNextResponse.json()  
                # change bookId[_id] to bookId[id]
                #toReadNext['id'] = toReadNext.pop('_id')              
                return toReadNext
            else:
                return None #JsonResponse({'message_error': toReadNextResponse.text}, status=400)
        except:
            return None #JsonResponse({'message_error': 'error in getting to read next book.'}, status=400)
        
def getReadingGoal(request):
    try:
        userToken = request.session.get('token')
        headers = {'x-auth-token': userToken}
        response = requests.get(f'{domainName}/api/users/getreadinggoal', headers=headers)
        if response.status_code == 200:
            readingGoal = response.json()
            #print("readingGoal ",readingGoal)
            return readingGoal.get('readingGoal')
        else:
            return None
    except:
        return None 

def setReadingGoal(request):
    try:
        userToken = request.session.get('token')
        headers = {'x-auth-token': userToken}
        readingGoal = request.POST.get('user_challenge[goal]')
        data = {'readingGoal': readingGoal}
        response = requests.post(f'{domainName}/api/users/setreadinggoal', json=data, headers=headers)
        if response.status_code == 201:
            messages.success(request, 'Reading goal set successfully')
            return redirect('userProfile:userhome')
        else:
            messages.error(request, response.text)
            return redirect('userProfile:userhome')
    except:
        messages.error(request, 'Error occured while setting reading goal')
        return redirect('userProfile:userhome')

def getReadCount(request):
    try:
        userToken = request.session.get('token')
        headers = {'x-auth-token': userToken}
        response = requests.get(f'{domainName}/api/users/ratedbooks', headers=headers)
        if response.status_code == 200:
            readCount = response.json()
            return readCount.get('count')
        else:
            return None
    except:
        return None 

def getCurrentBook (request):
    try:
        headers = {'x-auth-token':request.session['token'] }
        response = requests.get(f'{domainName}/api/users/CurrentBook', headers=headers)
        if response.status_code == 200:
            book = response.json()
            #book['id'] = book.pop('_id')
            return book
        else:
            return None
    except:
        return None         
# Create your views here.
def UserProfile(request):
    toReadNext = getToReadNext(request)
    readingGoal = getReadingGoal(request)
    readCount = getReadCount(request)
    currentBook = getCurrentBook(request)
    print("readCount ",readCount)
    print("currentBook ",currentBook)
    print("toReadNext ",toReadNext)
    return render(request, "userprofile/userhome.html", {'toReadNext': toReadNext, 'readingGoal': readingGoal, 'readCount': readCount, 'currentBook': currentBook})
    

class UserRecommendations(View):
    def get(self, request):
        try:
            userToken = request.session.get('token')
            headers = {'x-auth-token': userToken}
            recommendationsResponse = requests.get(f'{domainName}/api/books/recommend', headers=headers)
            if recommendationsResponse.status_code == 200:
                recommendations = recommendationsResponse.json()
                return  JsonResponse({'recommendations': recommendations}, status=200)
            else:
                return JsonResponse({'message_error': recommendationsResponse.text}, status=400)
        except:
            return JsonResponse({'message_error': 'error in getting recommendations.'}, status=400)
        

    # def get(self, request):
    #     recommendations = self.getRecommendedBooks(request)
    #     if recommendations:
    #         #print("recommendations ",recommendations)
    #         for x in recommendations:
    #             x['id'] = x.pop('_id')
    #         return render(request, "userprofile/recommendations.html", {'recommendations': recommendations})
    #     else:
    #         messages.error(request, 'Error occured while getting recommendations')
    #         return render(request, "userprofile/recommendations.html", {'recommendations': []})
        
class recommendationsPage(View):
    def get(self, request):
        return render(request, "userprofile/recommendations.html")
    
class UserBooks(View):
    def get(self,request):
        try:
            userToken = request.session.get('token')
            headers = {'x-auth-token': userToken}
            booksResponse = requests.get(f'{domainName}/api/users/readbooks', headers=headers)
            if booksResponse.status_code == 201:
                books = booksResponse.json()
                #book has bookId which includes all the details of the book
                #rename bookId[_id] to bookId[id]

                for book in books:
                    book['bookId']['id'] = book['bookId'].pop('_id')

                return render(request, "userprofile/userbooks.html", {'books': books})
            else:
                print("error occured")
                return render(request, "userprofile/userbooks.html", {'books': []})
        except:
            print(request, "error occured")
            return render(request, "userprofile/userbooks.html", {'books': []})
            

class tbrBooks(View):
    def get(self,request):
        try:
            userToken = request.session.get('token')
            headers = {'x-auth-token': userToken}
            booksResponse = requests.get(f'{domainName}/api/users/wanttoread', headers=headers)
            if booksResponse.status_code == 201:
                books = booksResponse.json()
                for book in books:
                    book['id'] = book.pop('_id')
                return render(request, "userprofile/tbrbooks.html", {'books': books})
            else:
                print("error occured")
                return render(request, "userprofile/tbrbooks.html", {'books': []})
        except:
            print(request, "error occured")
            return render(request, "userprofile/tbrbooks.html", {'books': []})
    
class rateBook(View):
    def post(self,request):
        bookId = request.POST.get('fe_eh')
        rating = request.POST.get('rating')
        
        try:
            userToken = request.session.get('token')
            headers = {'x-auth-token': userToken}
            data = {'bookId': bookId, 'rating': rating}
            response = requests.post(f'{domainName}/api/books/'+ str(bookId)+'/rating', json=data, headers=headers)
            if response.status_code == 201:
                messages.success(request, 'Book rated successfully')
                return redirect('userProfile:userbooks')
            else:
                messages.error(request, 'Error occured while rating book1')
                return redirect('userProfile:userbooks')
        except:
            messages.error(request, 'Error occured while rating book2')
            return redirect('userProfile:userbooks')
        
class reviewBook(View):
    def post(self,request):
        bookId = request.POST.get('bookIdentifier')
        review = request.POST.get('reviewText')
        #print("bookId",bookId)
        #print("review",review)

        try:
            userToken = request.session.get('token')
            headers = {'x-auth-token': userToken}
            data = {'review': review}
            response = requests.post(f'{domainName}/api/books/'+ str(bookId)+'/review', json=data, headers=headers)
            if response.status_code == 201:
                return redirect('userProfile:userbooks')
            else:
                print(response.status_code, response.text)
                return redirect('userProfile:userbooks')
        except:
            return redirect('userProfile:userbooks')
       
class setToReadNext(View):
    def post(self,request):
        bookId = request.POST.get('book_id')
        print("bookId",bookId)
        response = toReadNext(request, bookId)
        if response:
            if 'message_success' in response:
                messages.success(request, response['message_success'])
                return redirect('userProfile:tbrbooks')
            else:
                messages.error(request, response['message_error'])
                return redirect('userProfile:tbrbooks')
        else:
            messages.error(request, 'Error occured while setting book to read next')
            return redirect('userProfile:tbrbooks')
##################################
def similarBooks(genre):
        try:
            response = requests.get(f'{domainName}/api/books/genre/', params={'pageNumber': 1, 'genre': genre})
            if response.status_code == 200:
                books = response.json()
                return books
            else:
                return None
        except: 
            return None
def getAllGenreBooks(pageNumber):
    try:
        response =  requests.get(f'{domainName}/api/books/getbooks?page='+str(pageNumber))
        if response.status_code == 200:
            books = response.json()
            return books
        else:
            return None
    except: 
        return None  
    
def addToWantToRead(request, book_id):
    try:
        userToken = request.session.get('token')

Frontend/website/templates/userprofile/booksreadtable.html
{% load static %}
<div>
  {% include 'partials/_messages.html' %}
  <form class="d-flex" role="search" method="POST" action="{%  url 'userProfile:search-in-read' %}">
    {% csrf_token %}
    <input type="hidden" name="current_page" value={{request.path}} />
    <input
      class="form-control mx-2"
      type="search"
      placeholder="Title/ISBN"
      aria-label="Search"
      name ="query"
    />
    <button class="btn btn-outline-success me-2" type="submit">
      Search
    </button>
  </form>
  <div class="table" id="blur">
    <div class="table-header">Books read</div>
    <table cellspacing="0">
      <tr>
        <th>Picture</th>
        <th>Name</th>
        <th>Genres</th>
        <th>My rating</th>
        <th width="230">My review</th>
        <th>View book</th>
        <th>Delete</th>
      </tr>
      {% if books|length == 0 %}
        <tr>
          <td colspan="7" class="text-center">No books read yet</td>
        </tr>
      {% else %}

        {% for book in books %}
        <tr>
          <td>
            <img
              class="table-img"
              src="{{book.bookId.imageUrl}}"
              alt=""
            />
          </td>
          <td>{{book.bookId.title}}</td>
          <td>{% if book.bookId.genres %}{{book.bookId.genres}}{% else %}-{% endif %}</td>
          {% if book.rating %}
          <td>{{book.rating}}/5 <br>
            <button
              class="btn btn-sm btn-link mt-2"
              data-bs-toggle="modal" 
              data-bs-target="#rateBackdrop{{book.bookId.id}}"
            >
              Edit
            </button>
            {% include 'partials/_rate_modal.html'%}
          </td>
          {% else %}
          <td>
            <button
              class="btn btn-sm btn-outline-primary mt-2"
              data-bs-toggle="modal" 
              data-bs-target="#rateBackdrop{{book.bookId.id}}"
            >
              Rate
            </button>
            {% include 'partials/_rate_modal.html'%}
          </td>
          {% endif %}

          {% if book.userReview %}
          <td>{{book.userReview}} <br>
            <button
              class="btn btn-sm btn-link mt-2"
              data-bs-toggle="modal" 
              data-bs-target="#staticBackdrop{{book.bookId.id}}"
            >
              Edit
            </button>
            {% include 'partials/_review_modal.html'%}
          </td>
          {% else %}
          <td>
            <button
              class="btn btn-sm btn-outline-primary mt-2"
              data-bs-toggle="modal" 
              data-bs-target="#staticBackdrop{{book.bookId.id}}"
            >
              Write review
            </button>
            {% include 'partials/_review_modal.html'%}
          </td>
          {% endif %}
          <td>
            <a href="{% url 'userProfile:book-details' book_id=book.bookId.id %}"class="btn btn-sm btn-outline-primary mt-2">View</a>
          </td>
          <td>
            <a type ="button" class="btn btn-sm btn-outline-danger" href="{% url 'userProfile:delete-read' book_id=book.bookId.id rating=book.rating %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
              <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6Z"/>
              <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1ZM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118ZM2.5 3h11V2h-11v1Z"/>
            </svg>
          </a>
          </td>
        </tr>
        {% endfor %}
      {% endif %}
      
    </table>
  </div>
</div>

Frontend/website/templates/userprofile/browseBooks.html
{% extends 'userprofile/userprofile_base.html' %} {% load static %} {% block content %}
<div class="container-fluid">
    <div class="row">
        {% include 'partials/_sidebar.html'%}
        <div class="col-md-9 ms-sm-auto col-lg-10 px-md-4 mt-3">
            {% include 'partials/browsebooksalbum.html' %}
        </div>
        
</div>
</div>
{% endblock %}       

Frontend/website/templates/userprofile/recommendations.html
{% extends 'userprofile/userprofile_base.html' %} {% load static %} {% block content %}
<script  defer src="{% static 'js/spinner.js' %}"></script>
<div class = "inner-wrapper">
  <div id ="spinner-box" class="text-center mt-3 spinner-box" >
    <div class="spinner-border text-info" role="status"></div>
  </div>
  <div id="data-box">
    <!-- {% if recommendations %}
            <div>
                <h1>Recommended for you!</h1>
            </div>
            <div class="cards-container">
              
              {% for book in recommendations %}
              <a href="{% url 'userProfile:book-details' book_id=book.id %}" style="text-decoration: none;">
                <div class="card shadow p-3 mb-3 bg-body rounded" style="min-width: 300px">
                <div class="inner-card">
                  <img
                  src="{{book.imageUrl}}"
                  height="210"
                  width="130" 
                  />
                  <div class="card-body">
                    <h5 class="card-title">#{{forloop.counter}}: {{book.title}}</h5>
                    <p class="card-text">
                      {{book.authors|join:','}}
                    </p>
                    <p class="card-text">
                      Average book rating : {{book.avgRating}}/5
                    </p>
                  </div>
                </div>
              </div>
             </a>
              {% endfor %}

              {% else %}
              <div class="mb-6">
                <h1>Sorry, we couldn't find any recommendations for you! </h1>
                <a href="{% url 'userProfile:get-genre' genre='all' pageNumber='1' %}" >Rate some books</a>
              </div>

            </div>

         
    {% endif %} -->
  </div>
  </div> <!-- inner-wrapper -->

    <style>
      .card:hover {
        transform: scale(1.03);
        box-shadow: 0 0 11px rgba(33,33,33,.7); 
      }
    </style>  
{% endblock %}

Frontend/website/templates/userprofile/tbrBooks.html
{% extends 'userprofile/userprofile_base.html' %} {% load static %} {% block content %}
<link href="{% static 'css/tables.css'%}" rel="stylesheet" />
<div class="container-fluid">
    <div class="row">
        {% include 'partials/_user_sidebar.html'%}
        <div class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
          {% include 'userprofile/tbrTable.html' %}
    </div>
</div>
</div>
{% endblock %}       

Frontend/website/templates/userprofile/tbrTable.html
{% load static %}
{% include 'partials/_messages.html' %}
<form class="d-flex" role="search" method="POST" action="{%  url 'userProfile:search-in-tbr' %}">
  {% csrf_token %}
  <input type="hidden" name="current_page" value={{request.path}} />
  <input
    class="form-control mx-2"
    type="search"
    placeholder="Title/ISBN"
    aria-label="Search"
    name ="query"
  />
  <button class="btn btn-outline-success me-2" type="submit">
    Search
  </button>
</form>
<div class="table">
    <div class="table-header">Want to read</div>
    <table cellspacing="0">
      <tr>
        <th>Picture</th>
        <th>Name</th>
        <th>Genres</th>
        <th>Similar books</th>
        <th></th>
        <th>Delete</th>
      </tr>
      {% if books|length == 0 %}
      <tr>
        <td colspan="6" class="text-center">No books read yet</td>
      </tr>
    {% else %}
      {% for book in books %}
      <tr>
        <td>
          <img
            class="table-img"
            src="{{book.imageUrl}}"
            alt=""
          />
        </td>
        <td>{{book.title}}</td>
        <td>{% if book.genres %}{{book.genres}}{% else %}-{% endif %}</td>
        <td>
          <a href="{% url 'userProfile:book-details' book_id=book.id %}"class="btn btn-sm btn-outline-primary mt-2">View</a>
        </td>
        <td>
          <form method="POST" action="{% url 'userProfile:to-read-next' %}">
            {% csrf_token %}
            <input type="hidden" name="book_id" value="{{ book.id }}" />
            <button type = "submit" class="btn btn-sm btn-outline-primary mt-2">Read Next</button>
          </form>
        </td>
        <td>
          <a type ="button" class="btn btn-sm btn-outline-danger" href="{% url 'userProfile:delete-tbr' book_id=book.id %}">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6Z"/>
            <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1ZM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118ZM2.5 3h11V2h-11v1Z"/>
          </svg>
          </a>
        </td>
      </tr>
      {% endfor %}
    {% endif %}

    </table>
  </div>
</div>

Frontend/website/templates/userprofile/userbooks.html
{% extends 'userprofile/userprofile_base.html' %} {% load static %} {% block content %}
<link href="{% static 'css/tables.css'%}" rel="stylesheet" />
<div class="container-fluid">
    <div class="row">
        {% include 'partials/_user_sidebar.html'%}
        <div class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
          {% include 'userprofile/booksreadtable.html' %}
    </div>
</div>
</div>
{% endblock %}       

Frontend/website/templates/userprofile/userhome.html
{% extends 'userprofile/userprofile_base.html' %} {% load static %} {% block content %}
<div class = "inner-wrapper">
  {% include 'partials/_messages.html' %}

          <div
            class="row row-cols-1 row-cols-sm-1 row-cols-md-2 row-cols-lg-3 g-3 mb-5"
          >
            <div class="col">
              <div class="card mx-5 shadow-sm" style="width: 12rem">
                <div class="card-header"># Books read</div>
                <div class="card-body text-center">
                  <h5 class="card-title">{{readCount}}</h5>
                  <p class="card-text">Reading Goal : {{readingGoal}}</p>
                  <button
                    class="btn btn-sm btn-link"
                    data-bs-toggle="modal" 
                    data-bs-target="#readingGoalModal"
                  >
                    Edit
                  </button>
                  {% include 'partials/_readingGoal_modal.html'%}
                </div>
              </div>
            </div>
            <div class="col">
              {% if currentBook %}
              <a href="{% url 'userProfile:book-details' book_id=currentBook.id %}" style="text-decoration: none;">
              {% endif %}
              <div class="card mx-5 shadow-sm" style="width: 12rem">
                <img
                  src="{{currentBook.imageUrl}}"
                  class="bd-placeholder-img card-img-top"
                  height="260"
                />
                <div class="card-header">Currently Reading</div>
                <div class="card-body text-center">
                  <h5 class="card-title">{{currentBook.title}}</h5>
                </div>
              </div>
              {% if currentBook %}
              </a>
              {% endif %}
            </div>
            <div class="col">
              {% if toReadNext %}
              <a href="{% url 'userProfile:book-details' book_id=toReadNext.id %}" style="text-decoration: none;">
              {% endif %}
              <div class="card mx-5 shadow-sm" style="width: 12rem">
                <img
                  src="{{toReadNext.imageUrl}}"
                  class="bd-placeholder-img card-img-top"
                  height="260"
                />
                <div class="card-header">Want to read next</div>
                <div class="card-body text-center">
                  <h5 class="card-title">{{toReadNext.title}}</h5>
                </div>
              </div>
              {% if toReadNext %}
              </a>
              {% endif %}
            </div>
          </div>
        </div>
{% endblock %}       
<!-- {% url 'userProfile:to-read-next' %} -->

Frontend/website/templates/userprofile/userprofile_base.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>NextReads</title>

    <link href="{% static 'css/userprofile.css'%}" rel="stylesheet" />
    <link href="{% static 'css/bootstrap.css'%}" rel="stylesheet" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Satisfy&family=Source+Sans+Pro:ital,wght@0,200;0,300;0,400;0,700;1,200;1,300;1,400;1,900&display=swap" rel="stylesheet">
    <!-- Custom styles for this template -->
  </head>

  <body>
    {% include 'partials/profileNavbar.html' %}
    <main>
      <div class="main-content-wrapper">
        
        {% block content %} {% endblock %}

    </div>
    </main>
    <!-- {% include 'partials/profileFooter.html' %} -->
  </body>
  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

</html>