Frontend/website/userProfile/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt
from .views import UserProfile, UserRecommendations, UserBooks, tbrBooks, rateBook
app_name = 'userProfile'
urlpatterns = [
    path('recommendations', views.UserRecommendations.as_view(), name='userrecommendations'),
    path('recommendationsPage', views.recommendationsPage.as_view(), name='userrecommendationspage'),
    path('userhome', views.UserProfile, name='userhome'),
    path('userbooks', views.UserBooks.as_view(), name='userbooks'),
    path('tbrbooks', views.tbrBooks.as_view(), name='tbrbooks'),
    #path('browsebooks',views.browseBooks.as_view(), name='browseBooks'),
    path('userbooks/ratebook', views.rateBook.as_view(), name='ratebook'),
    path('userbooks/reviewbook', views.reviewBook.as_view(), name='reviewbook'),
    path('userhome/to-read-next', views.setToReadNext.as_view(), name='to-read-next'),
    path('book/<str:book_id>', views.bookDetails, name='book-details'),
    path('browseBooks/genre/<str:genre>/<int:pageNumber>', views.getGenre, name='get-genre'),
    path('browseBooks/want-to-read-browse', views.wantToReadBrowse, name='want-to-read-browse'),
    path('book/want-to-read/<str:book_id>', views.wantToReadBookDetails, name='want-to-read-book-details'),
    path('search', views.searchBooks, name='search-books'),
    path('searchinread', views.searchInRead, name='search-in-read'),
    path('searchintbr', views.searchInTbr, name='search-in-tbr'),
    path('setreadinggoal', views.setReadingGoal, name='set-reading-goal'),
    path('deletetbr/<str:book_id>',views.deleteFromTbr, name='delete-tbr'),
    path('deleteread/<str:book_id>/<int:rating>',views.deleteFromRead, name='delete-read'),
    path('setcurrentbook/<str:book_id>',views.setCurrentBook, name='set-current-book'),

]

Frontend/website/website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('mainPage.urls')),
    path('authentication/', include('authentication.urls')),
    path("admin/", admin.site.urls),
    path('userProfile/', include('userProfile.urls')),

]

Frontend/website/templates/partials/_messages.html
{% if messages %}
<div class="messages">
    {% for message in messages %}
    <div{% if message.tags %} class=" alert alert-sm alert-{{ message.tags }}" id="msg-container"{% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}
<script>
  var msgContainer = document.getElementById("msg-container");
    if (msgContainer) {
        setTimeout(function () {
        msgContainer.remove();
        }, 2000);
    }

</script>

Frontend/website/templates/partials/_navbar.html
{% load static %}

    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <div class="container-fluid">
        <img class= "rounded" width="80" height = "60"src="{% static 'img/logo.png'%}">
        <a class="navbar-brand" href="/">NextReads</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Books</a>
            </li>
            <li class="nav-item">
              <a class="nav-link">Browse</a>
            </li>
          </ul>

          <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Title / ISBN" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>

          <div class="d-flex mb-3">
            <button class="btn btn-link ms-2">Sign in</a>
            <button class="btn btn-link ms-2">Join</a>
          </div>
          
        </div>

      </div>
    </nav>
  

Frontend/website/templates/partials/_rate_modal.html
{% load static %}
<!-- model rate -->
<div class="modal fade" id="rateBackdrop{{book.bookId.id}}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="rateBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="rateBackdropLabel">Rate</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p style="color:black"> {{book.bookId.title}}</p>
          <form method="POST" action="{%  url 'userProfile:ratebook' %}">
            {% csrf_token %}
            <input type="hidden" name="fe_eh" value={{book.bookId.id}} /> 
            <div class="mb-3">
              <label for="message-text" class="col-form-label" style="color:black">Rate:</label>
              <input class="inputNumber" placeholder="#" min="1" max="5" type="number" name="rating" required/>
            </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-primary">Save</button>
            </div>
          </form>
      </div>
    </div>
  </div>
  <!-- -->

Frontend/website/templates/partials/_readingGoal_modal.html
{% load static %}
<!-- model rate -->
<div class="modal fade" id="readingGoalModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="rateBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="readingGoalModalLabel">Set new reading goal</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form method="POST" action="{% url 'userProfile:set-reading-goal' %}" >
            {% csrf_token %}
            <div class="mb-3">
                I want to read
                <input class="inputNumber" placeholder="#" min="0" type="number" name="user_challenge[goal]" id="user_challenge_goal" />
                books in 2023.
            </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-primary">Save</button>
            </div>
          </form>
      </div>
    </div>
  </div>
  <!-- -->

Frontend/website/templates/partials/_register_sidebar.html
{% load static %}
<nav
id="sidebarMenu"
class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse"
>
<div class="position-sticky pt-3 sidebar-sticky">
  <form class="d-flex" role="search" method="POST" action="{%  url 'search-books' %}">
    {% csrf_token %}
    <input type="hidden" name="current_page" value={{request.path}} />
    <input
      class="form-control mx-2"
      type="search"
      placeholder="Title/ISBN"
      aria-label="Search"
      name ="query"
    />
    <button class="btn btn-outline-success me-2" type="submit">
      Search
    </button>
  </form>
  <ul class="nav flex-column">
    <li class="nav-item">
      <a class="nav-link active" aria-current="page" href="{% url 'get-genre' genre='all' pageNumber='1' %}">
        <span data-feather="home" class="align-text-bottom"></span>
        All books
      </a>
      <a class="nav-link" aria-current="page" href="{% url 'get-genre' genre='non-fiction' pageNumber='1' %}">
        <span data-feather="home" class="align-text-bottom"></span>
        Non-Fiction
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'get-genre' genre='fiction' pageNumber='1' %}">
        <span data-feather="file" class="align-text-bottom"></span>
        Fiction
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'get-genre' genre='history' pageNumber='1' %}">
        <span data-feather="file" class="align-text-bottom"></span>
        Histroy
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'get-genre' genre='science-fiction' pageNumber='1' %}">
        <span data-feather="users" class="align-text-bottom"></span>
        Science-fiction
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'get-genre' genre='young' pageNumber='1' %}">
        <span data-feather="users" class="align-text-bottom"></span>
        Young adult
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'get-genre' genre='mystery' pageNumber='1' %}">
        <span data-feather="layers" class="align-text-bottom"></span>
        Mystery
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'get-genre' genre='fantasy' pageNumber='1' %}">
        <span data-feather="layers" class="align-text-bottom"></span>
        Fantasy
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'get-genre' genre='romance' pageNumber='1' %}">
        <span data-feather="layers" class="align-text-bottom"></span>
        Romance
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'get-genre' genre='paranormal' pageNumber='1' %}">
        <span data-feather="layers" class="align-text-bottom"></span>
        Paranormal
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'get-genre' genre='thriller' pageNumber='1' %}">
        <span data-feather="layers" class="align-text-bottom"></span>
        Thriller
      </a>
    </li>
  </ul>
</div>
</nav>

Frontend/website/templates/partials/_review_modal.html
{% load static %}
  <!-- model review -->
  <div class="modal fade" id="staticBackdrop{{book.bookId.id}}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel">Write a review for:</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p style="color:black" > {{book.bookId.title}}</p>
          <form method="POST" action="{%  url 'userProfile:reviewbook' %}">
            {% csrf_token %}
            <input type="hidden" name="bookIdentifier" value={{book.bookId.id}} /> 
            <div class="mb-3">
              <label for="message-text" class="col-form-label" style="color:black">Review:</label>
              <textarea class="form-control" id="message-text" name="reviewText" required></textarea>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Save</button>
              </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  <!-- -->

Frontend/website/templates/partials/_sidebar.html
{% load static %}
<nav
id="sidebarMenu"
class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse"
>
<div class="position-sticky pt-3 sidebar-sticky" style="margin-top: 5.5rem">
  <form class="d-flex" role="search" method="POST" action="{%  url 'userProfile:search-books' %}">
    {% csrf_token %}
    <input type="hidden" name="current_page" value={{request.path}} />
    <input
      class="form-control mx-2"
      type="search"
      placeholder="Title/ISBN"
      aria-label="Search"
      name ="query"
    />
    <button class="btn btn-outline-success me-2" type="submit">
      Search
    </button>
  </form>
  <ul class="nav flex-column">
    <li class="nav-item">
      <a class="nav-link active" aria-current="page" href="{% url 'userProfile:get-genre' genre='all' pageNumber='1'%}">
        <span data-feather="home" class="align-text-bottom"></span>
        All books
      </a>
      <a class="nav-link" aria-current="page" href="{% url 'userProfile:get-genre' genre='non-fiction' pageNumber='1'%}">
        <span data-feather="home" class="align-text-bottom"></span>
        Non-Fiction
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'userProfile:get-genre' genre='fiction' pageNumber='1'%}">
        <span data-feather="file" class="align-text-bottom"></span>
        Fiction
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'userProfile:get-genre' genre='history' pageNumber='1'%}">
        <span data-feather="file" class="align-text-bottom"></span>
        Histroy
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'userProfile:get-genre' genre='science-fiction'  pageNumber='1'%}">
        <span data-feather="users" class="align-text-bottom"></span>
        Science-fiction
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'userProfile:get-genre' genre='young'  pageNumber='1'%}">
        <span data-feather="users" class="align-text-bottom"></span>
        Young adult
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'userProfile:get-genre' genre='mystery' pageNumber='1'%}">
        <span data-feather="layers" class="align-text-bottom"></span>
        Mystery
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'userProfile:get-genre' genre='fantasy' pageNumber='1'%}">
        <span data-feather="layers" class="align-text-bottom"></span>
        Fantasy
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'userProfile:get-genre' genre='romance' pageNumber='1'%}">
        <span data-feather="layers" class="align-text-bottom"></span>
        Romance
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'userProfile:get-genre' genre='paranormal' pageNumber='1'%}">
        <span data-feather="layers" class="align-text-bottom"></span>
        Paranormal
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'userProfile:get-genre' genre='thriller' pageNumber='1'%}">
        <span data-feather="layers" class="align-text-bottom"></span>
        Thriller
      </a>
    </li>
  </ul>
</div>
</nav>

Frontend/website/templates/partials/_user_sidebar.html
{% load static %}
<nav
id="sidebarMenu"
class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse"
>
<div class="position-sticky pt-3 sidebar-sticky">

  <ul class="nav flex-column">
    <li class="nav-item">
      <a class="nav-link active" aria-current="page" href="/userProfile/userbooks">
        <span data-feather="home" class="align-text-bottom"></span>
        Books read
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/userProfile/tbrbooks">
        <span data-feather="file" class="align-text-bottom"></span>
        Want to read
      </a>
    </li>    
  </ul>
</div>
</nav>

Frontend/website/templates/partials/browse_book_card.html
{% load static %}
<link href="{% static 'css/registerr.css'%}" rel="stylesheet" />
<a href="{% url 'userProfile:book-details' book_id=book.id %}" style="text-decoration: none;">
<div class="col">
    <div class="card shadow-sm h-100">
      <div class="mx-1 my-1">
        <div class="d-flex justify-content-center align-items-center">
          <img
            src="{{book.imageUrl}}"
            class=""
            height="210"
            width="130"
          />
      </div>
      </div>
      <div class="card-body text-center">
        <p class="card-text">{{book.title}}</p>
        <div class="justify-content-between align-items-center">
          <form method="POST" action="{% url 'userProfile:ratebook' %}">
            {% csrf_token %}
            <!-- <div class="mb-3">
              <input type="hidden" name="book_id" value="{{ book.id }}" />
              <label for="message-text" class="col-form-label">Rate:</label>
              <input class="inputNumber" placeholder="rate" min="0" max="5" type="number" name="rating" required/>
              <button type="submit" >Save</button>
            </div> -->
            <input type="hidden" name="fe_eh" value="{{ book.id }}" />
            <span class="star-rating">
              <input  type="radio" name="rating" value="1"><i></i>
              <input  type="radio" name="rating" value="2"><i></i>
              <input  type="radio" name="rating" value="3"><i></i>
              <input  type="radio" name="rating" value="4"><i></i>
              <input  type="radio" name="rating" value="5"><i></i>
            </span>
            <button type="submit"  class="btn btn-sm btn-outline-secondary mt-2 ">Save rate</button>
            
            <!-- <div class="stars" data-rating="0">
              <button class="fa fa-star rmv-btn star1" value="1" title="did not like it" type="submit" name="rating"  ></button>
              <button class="fa fa-star rmv-btn star2" value="2" title="it was ok" type="submit" name="rating" ></button>
              <button class="fa fa-star rmv-btn star3" value="3" title="liked it" type="submit" name="rating"></button>
              <button class="fa fa-star rmv-btn star4" value="4" title="really liked it" type="submit" name="rating"></button>
              <button class="fa fa-star rmv-btn star5" value="5" title="it was amazing"type="submit" name="rating"></button>
            </div> -->
          </form>
          <form method="POST" action="{% url 'userProfile:want-to-read-browse' %}">
            {% csrf_token %}
            <input type="hidden" name="book_id" value="{{ book.id }}" />
            <button
              type="submit"
              class="btn btn-sm btn-outline-secondary mt-2 "
            >
              Want to read
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</a>
<style>
  .card:hover {
    transform: scale(1.05);
    box-shadow: 0 0 11px rgba(33,33,33,.7); 
  }
</style>

Frontend/website/templates/partials/browsebooksalbum.html
{% load static %}
{% include 'partials/_messages.html' %}

<div class="album bg-body-tertiary">
    <div class="container">
      <div
        class="row row-cols-2 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-5 g-3"
      >
      {% for book in books %}
      {% include 'partials/browse_book_card.html'%}
      {% endfor %}

       

      </div>
    </div>
  </div>

<div class="d-flex align-items-center justify-content-center my-2">
    <nav aria-label="Page navigation example">
      <ul class="pagination">
      <li class="page-item disabled">
        <a class="page-link">Previous</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="{% url 'userProfile:get-genre' genre='all' pageNumber='1' %}">1</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="{% url 'userProfile:get-genre' genre='all' pageNumber='2' %}" >2</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="{% url 'userProfile:get-genre' genre='all' pageNumber='3' %}">3</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="#">Next</a>
      </li>
      </ul>
  </nav> 
</div> 

Frontend/website/templates/partials/profileFooter.html
{% load static %}

<footer>
    <div class="contact-us">
      <h3>Contact Us</h3>
      <p>Phone: (123) 456-7890<br>Email: nextreads@gmail.com</p>
      <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
        <li class="ms-3"><a class="text-body-secondary" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"/></svg></a></li>
        <li class="ms-3"><a class="text-body-secondary" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"/></svg></a></li>
        <li class="ms-3"><a class="text-body-secondary" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"/></svg></a></li>
      </ul>
    </div>
    <div class="company-info">
      
      <p>Copyright © 2023 NextReads</p>
    </div>
  </footer>

Frontend/website/templates/partials/profileNavbar.html
{% load static %}
<header class="header">
  <div class="main-header-container">
    <div class="line-bar"></div>
    <div class="logo-container-class">
      <a href="/">
        <img src="{% static 'img/logo.png'%}" width="130px" alt="logo" />
      </a>
      <p>
        Looking for what to read next?<br />
        We have got you covered!
      </p>
      <div>
        <form action = "{% url 'logout' %}" method="POST">
          {% csrf_token %}
          <input class ='btn btn-primary' type="submit" value="Logout"/>
        </form>
      </div>
    </div>
    <nav class="nav-menu">
      <ul class="nav-list">
        <li class="nav-list-item">
          <a href="/userProfile/userhome">
            <span>Home</span>
          </a>
        </li>
        <li class="nav-list-item">
          <a href="/userProfile/userbooks">
            <span>My books</span>
          </a>
        </li>
        <li class="nav-list-item ">
          <a href="/userProfile/recommendationsPage">
            <span>Recommendations</span>
          </a>
        </li>
        <li class="nav-list-item">
          <a href="{% url 'userProfile:get-genre' genre='all' pageNumber='1' %}">
            <span>Browse</span>
          </a>
        </li>
      </ul>
      <button
      class="collapsed d-md-none"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#sidebarMenu"
      aria-controls="sidebarMenu"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span ></span>
    </button>
    </nav>
  </div>
</header>
<script>
  window.addEventListener("scroll", function () {
    var navMenu = document.querySelector(".nav-menu");
    var header = document.querySelector(".header");

    if (window.pageYOffset > navMenu.offsetTop) {
      header.classList.add("scrolled");
    } else {
      header.classList.remove("scrolled");
    }
  });
  // add active class to nav-list-item based on url
  const navListItems = document.querySelectorAll(".nav-list-item");
  const currentLocation = location.href;
  const navLinks = document.querySelectorAll(".nav-list-item a");
  for (let i = 0; i < navLinks.length; i++) {
    if (navLinks[i].href === currentLocation) {
      navListItems[i].classList.add("active");
    }
  }


  
</script>

Frontend/website/templates/partials/rate_book_card.html
{% load static %}
<div class="col">
    <div class="card shadow-sm h-100">
      <div class="d-flex justify-content-center align-items-center">
        <img
          src="{{book.imageUrl}}"
          class=""
          height="210"
          width="130"
        />
    </div>
      <div class="card-body text-center">
        <p class="card-text">{{book.title}}</p>
        <div class="justify-content-between align-items-center">
          <form method="POST" action="{% url 'rate-book' %}">
            {% csrf_token %}
            <!-- <div class="mb-3">
              <input type="hidden" name="book_id" value="{{ book.id }}" />
              <label for="message-text" class="col-form-label">Rate:</label>
              <input class="inputNumber" placeholder="rate" min="0" max="5" type="number" name="rating" required/>
              <button type="submit" >Save</button>
            </div> -->
            <input type="hidden" name="book_id" value="{{ book.id }}" />
            <span class="star-rating">
              <input  type="radio" name="rating" value="1"><i></i>
              <input  type="radio" name="rating" value="2"><i></i>
              <input  type="radio" name="rating" value="3"><i></i>
              <input  type="radio" name="rating" value="4"><i></i>
              <input  type="radio" name="rating" value="5"><i></i>
            </span>
            <button type="submit"  class="btn btn-sm btn-outline-secondary mt-2 ">Save rate</button>
            
            <!-- <div class="stars" data-rating="0">
              <button class="fa fa-star rmv-btn star1" value="1" title="did not like it" type="submit" name="rating"  ></button>
              <button class="fa fa-star rmv-btn star2" value="2" title="it was ok" type="submit" name="rating" ></button>
              <button class="fa fa-star rmv-btn star3" value="3" title="liked it" type="submit" name="rating"></button>
              <button class="fa fa-star rmv-btn star4" value="4" title="really liked it" type="submit" name="rating"></button>
              <button class="fa fa-star rmv-btn star5" value="5" title="it was amazing"type="submit" name="rating"></button>
            </div> -->
          </form>
          <form method="POST" action="{% url 'want-to-read' %}">
            {% csrf_token %}
            <input type="hidden" name="book_id" value="{{ book.id }}" />
            <button
              type="submit"
              class="btn btn-sm btn-outline-secondary mt-2 "
            >
              Want to read
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <style>
    .card:hover {
      transform: scale(1.05);
      box-shadow: 0 0 11px rgba(33,33,33,.7); 
    }
  </style>

Frontend/website/templates/partials/ratebooksalbum.html
{% load static %}
<div class="album bg-body-tertiary">
    <div class="container">
      <h5 class="text-center">
        Rate at least 5 books to continue
      </h5>
      <input type="hidden" id="rateCount" value="{{request.session.rateCount.count}}" />
      {% if request.session.rateCount.count %}
      <p class="text-center">You have rated {{request.session.rateCount.count}} books</p>
      {% else %}
      <p class="text-center">You have rated 0 books</p>
      {% endif %}
      <div
        class="row row-cols-2 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-5 g-3"
      >
      {% for book in books %}
        {% include 'partials/rate_book_card.html'%}
      {% endfor %}
       

      </div>
    </div>
  </div>

  <div class="d-flex align-items-center justify-content-center my-2">
    <nav aria-label="Page navigation example">
      <ul class="pagination">
      <li class="page-item disabled">
        <a class="page-link">Previous</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="{% url 'get-genre' genre='all' pageNumber='1' %}">1</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="{% url 'get-genre' genre='all' pageNumber='2' %}" >2</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="{% url 'get-genre' genre='all' pageNumber='3' %}">3</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="#">Next</a>
      </li>
      </ul>
  </nav> 
</div> 